# Makefile for busybox
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=
lib-$(CONFIG_APPKEY)	+= lib/appkey/appkey.o
lib-$(CONFIG_APPKEY)	+= app/appkey/appkey.o
lib-$(CONFIG_ATCOOKIE)  += app/atcookie/atcookie.o
lib-$(CONFIG_JLOGGER)	+= app/jlogger/jlogger.o
lib-$(CONFIG_JLOGD)    	+= app/jlogd/jlogd.o
lib-$(CONFIG_SMONITORC)	+= app/smonitorc/smonitorc.o
lib-$(CONFIG_SMONITORD)	+= app/smonitord/smonitord.o
lib-$(CONFIG_STIMERC)  	+= app/stimerc/stimerc.o
lib-$(CONFIG_STIMERD)  	+= app/stimerd/stimerd.o
lib-$(CONFIG_UMC)  	+= app/umc/umc.o
lib-$(CONFIG_UMD)  	+= app/umd/umd.o
lib-$(CONFIG_UMD)  	+= app/umd/cfg.o
lib-$(CONFIG_UMD)  	+= app/umd/cli.o
lib-$(CONFIG_UMD)  	+= app/umd/flow.o
lib-$(CONFIG_UMD)  	+= app/umd/timer.o
lib-$(CONFIG_UMD)  	+= app/umd/user.o
