# Makefile for busybox
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

lib-y:=
lib-$(CONFIG_AT_TTYUSB0)	+= app/3g/at_ttyUSB0.o
lib-$(CONFIG_AT_TTYUSB1)	+= app/3g/at_ttyUSB1.o
lib-$(CONFIG_AT_TTYUSB3)	+= app/3g/at_ttyUSB3.o
lib-$(CONFIG_PPP_DIAL)	+= app/3g/ppp_dial.o
lib-$(CONFIG_APPKEY)	+= lib/appkey/appkey.o
lib-$(CONFIG_APPKEY)	+= app/appkey/appkey.o
lib-$(CONFIG_ATCHECK)  	+= app/atcheck/atcheck.o
lib-$(CONFIG_ATCOOKIE)  += app/atcookie/atcookie.o
lib-$(CONFIG_ATDOG)    	+= app/atdog/atdog.o
lib-$(CONFIG_ATENV)    	+= app/atenv/atenv.o
lib-$(CONFIG_ATOTP)    	+= app/atotp/atotp.o
lib-$(CONFIG_ATRT)    	+= app/atrt/atrt.o
lib-$(CONFIG_ATSS)    	+= app/atss/atss.o
lib-$(CONFIG_ATSYS)    	+= app/atsys/atsys.o
lib-$(CONFIG_JLOGGER)	+= app/jlogger/jlogger.o
lib-$(CONFIG_JLOGD)    	+= app/jlogd/jlogd.o
lib-$(CONFIG_SINETD)   	+= app/sinetd/sinetd.o
lib-$(CONFIG_SMONITORC)	+= app/smonitorc/smonitorc.o
lib-$(CONFIG_SMONITORD)	+= app/smonitord/smonitord.o
lib-$(CONFIG_STIMERC)  	+= app/stimerc/stimerc.o
lib-$(CONFIG_STIMERD)  	+= app/stimerd/stimerd.o
lib-$(CONFIG_UMC)  	+= app/umc/umc.o
lib-$(CONFIG_UMD)  	+= app/umd/umd.o
lib-$(CONFIG_UMD)  	+= app/umd/cfg.o
lib-$(CONFIG_UMD)  	+= app/umd/cli.o
lib-$(CONFIG_UMD)  	+= app/umd/flow.o
lib-$(CONFIG_UMD)  	+= app/umd/timer.o
lib-$(CONFIG_UMD)  	+= app/umd/user.o
